# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files\reports.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReportsWindow(object):
    def setupUi(self, ReportsWindow):
        ReportsWindow.setObjectName("ReportsWindow")
        ReportsWindow.resize(600, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ReportsWindow.sizePolicy().hasHeightForWidth())
        ReportsWindow.setSizePolicy(sizePolicy)
        ReportsWindow.setMinimumSize(QtCore.QSize(600, 500))
        ReportsWindow.setMaximumSize(QtCore.QSize(600, 500))
        self.gridLayout = QtWidgets.QGridLayout(ReportsWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.egramReport = QtWidgets.QPushButton(ReportsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.egramReport.sizePolicy().hasHeightForWidth())
        self.egramReport.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.egramReport.setFont(font)
        self.egramReport.setObjectName("egramReport")
        self.verticalLayout.addWidget(self.egramReport)
        self.bradycardiaReport = QtWidgets.QPushButton(ReportsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bradycardiaReport.sizePolicy().hasHeightForWidth())
        self.bradycardiaReport.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.bradycardiaReport.setFont(font)
        self.bradycardiaReport.setAutoRepeatDelay(300)
        self.bradycardiaReport.setObjectName("bradycardiaReport")
        self.verticalLayout.addWidget(self.bradycardiaReport)
        self.tempReport = QtWidgets.QPushButton(ReportsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempReport.sizePolicy().hasHeightForWidth())
        self.tempReport.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.tempReport.setFont(font)
        self.tempReport.setObjectName("tempReport")
        self.verticalLayout.addWidget(self.tempReport)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(ReportsWindow)
        QtCore.QMetaObject.connectSlotsByName(ReportsWindow)

    def retranslateUi(self, ReportsWindow):
        _translate = QtCore.QCoreApplication.translate
        ReportsWindow.setWindowTitle(_translate("ReportsWindow", "Reports"))
        self.egramReport.setText(_translate("ReportsWindow", "Electrogram"))
        self.bradycardiaReport.setText(_translate("ReportsWindow", "Bradycardia Parameters"))
        self.tempReport.setText(_translate("ReportsWindow", "Temporary Parameters"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReportsWindow = QtWidgets.QDialog()
    ui = Ui_ReportsWindow()
    ui.setupUi(ReportsWindow)
    ReportsWindow.show()
    sys.exit(app.exec_())
