# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files\reports.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReportsWindow(object):
    def setupUi(self, ReportsWindow):
        ReportsWindow.setObjectName("ReportsWindow")
        ReportsWindow.resize(600, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ReportsWindow.sizePolicy().hasHeightForWidth())
        ReportsWindow.setSizePolicy(sizePolicy)
        ReportsWindow.setMinimumSize(QtCore.QSize(600, 500))
        ReportsWindow.setMaximumSize(QtCore.QSize(600, 500))
        self.gridLayout = QtWidgets.QGridLayout(ReportsWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.egram_btn = QtWidgets.QPushButton(ReportsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.egram_btn.sizePolicy().hasHeightForWidth())
        self.egram_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.egram_btn.setFont(font)
        self.egram_btn.setObjectName("egram_btn")
        self.verticalLayout.addWidget(self.egram_btn)
        self.brady_btn = QtWidgets.QPushButton(ReportsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brady_btn.sizePolicy().hasHeightForWidth())
        self.brady_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.brady_btn.setFont(font)
        self.brady_btn.setAutoRepeatDelay(300)
        self.brady_btn.setObjectName("brady_btn")
        self.verticalLayout.addWidget(self.brady_btn)
        self.temp_btn = QtWidgets.QPushButton(ReportsWindow)
        self.temp_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_btn.sizePolicy().hasHeightForWidth())
        self.temp_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.temp_btn.setFont(font)
        self.temp_btn.setCheckable(False)
        self.temp_btn.setAutoExclusive(False)
        self.temp_btn.setDefault(False)
        self.temp_btn.setFlat(False)
        self.temp_btn.setObjectName("temp_btn")
        self.verticalLayout.addWidget(self.temp_btn)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(ReportsWindow)
        QtCore.QMetaObject.connectSlotsByName(ReportsWindow)

    def retranslateUi(self, ReportsWindow):
        _translate = QtCore.QCoreApplication.translate
        ReportsWindow.setWindowTitle(_translate("ReportsWindow", "Reports"))
        self.egram_btn.setText(_translate("ReportsWindow", "Electrogram"))
        self.brady_btn.setText(_translate("ReportsWindow", "Bradycardia Parameters"))
        self.temp_btn.setText(_translate("ReportsWindow", "Temporary Parameters"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReportsWindow = QtWidgets.QDialog()
    ui = Ui_ReportsWindow()
    ui.setupUi(ReportsWindow)
    ReportsWindow.show()
    sys.exit(app.exec_())
