# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcomescreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WelcomeScreen(object):
    def setupUi(self, WelcomeScreen):
        WelcomeScreen.setObjectName("WelcomeScreen")
        WelcomeScreen.resize(640, 269)
        self.label = QtWidgets.QLabel(WelcomeScreen)
        self.label.setGeometry(QtCore.QRect(10, 10, 621, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.registerButton = QtWidgets.QPushButton(WelcomeScreen)
        self.registerButton.setGeometry(QtCore.QRect(190, 80, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.registerButton.setFont(font)
        self.registerButton.setObjectName("registerButton")
        self.loginButton = QtWidgets.QPushButton(WelcomeScreen)
        self.loginButton.setGeometry(QtCore.QRect(190, 170, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")

        self.retranslateUi(WelcomeScreen)
        QtCore.QMetaObject.connectSlotsByName(WelcomeScreen)

    def retranslateUi(self, WelcomeScreen):
        _translate = QtCore.QCoreApplication.translate
        WelcomeScreen.setWindowTitle(_translate("WelcomeScreen", "Dialog"))
        self.label.setText(_translate("WelcomeScreen", "Welcome to the SFWRENG 3K04 DCM Interface"))
        self.registerButton.setText(_translate("WelcomeScreen", "Register a new user"))
        self.loginButton.setText(_translate("WelcomeScreen", "Login as an existing user"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WelcomeScreen = QtWidgets.QWidget()
    ui = Ui_WelcomeScreen()
    ui.setupUi(WelcomeScreen)
    WelcomeScreen.show()
    sys.exit(app.exec_())
